#ifndef ANSI_ESC_ANSI_ESC_H_
#define ANSI_ESC_ANSI_ESC_H_

#include <stdint.h>

#define ANSI_ESC_CSI "\x1b["

#define ANSI_ESC_RESET ANSI_ESC_CSI "0m"
#define ANSI_ESC_BOLD ANSI_ESC_CSI "1m"
#define ANSI_ESC_DIM ANSI_ESC_CSI "2m"
#define ANSI_ESC_UNDERLINE ANSI_ESC_CSI "4m"
#define ANSI_ESC_BLINK ANSI_ESC_CSI "5m"
#define ANSI_ESC_REVERSE ANSI_ESC_CSI "7m"
#define ANSI_ESC_HIDDEN ANSI_ESC_CSI "8m"

#define ANSI_ESC_FG_BLACK ANSI_ESC_CSI "30m"
#define ANSI_ESC_FG_RED ANSI_ESC_CSI "31m"
#define ANSI_ESC_FG_GREEN ANSI_ESC_CSI "32m"
#define ANSI_ESC_FG_YELLOW ANSI_ESC_CSI "33m"
#define ANSI_ESC_FG_BLUE ANSI_ESC_CSI "34m"
#define ANSI_ESC_FG_MAGENTA ANSI_ESC_CSI "35m"
#define ANSI_ESC_FG_CYAN ANSI_ESC_CSI "36m"
#define ANSI_ESC_FG_WHITE ANSI_ESC_CSI "37m"

#define ANSI_ESC_BG_BLACK ANSI_ESC_CSI "40m"
#define ANSI_ESC_BG_RED ANSI_ESC_CSI "41m"
#define ANSI_ESC_BG_GREEN ANSI_ESC_CSI "42m"
#define ANSI_ESC_BG_YELLOW ANSI_ESC_CSI "43m"
#define ANSI_ESC_BG_BLUE ANSI_ESC_CSI "44m"
#define ANSI_ESC_BG_MAGENTA ANSI_ESC_CSI "45m"
#define ANSI_ESC_BG_CYAN ANSI_ESC_CSI "46m"
#define ANSI_ESC_BG_WHITE ANSI_ESC_CSI "47m"

#define ANSI_ESC_FG_BRIGHT_BLACK ANSI_ESC_CSI "90m"
#define ANSI_ESC_FG_BRIGHT_RED ANSI_ESC_CSI "91m"
#define ANSI_ESC_FG_BRIGHT_GREEN ANSI_ESC_CSI "92m"
#define ANSI_ESC_FG_BRIGHT_YELLOW ANSI_ESC_CSI "93m"
#define ANSI_ESC_FG_BRIGHT_BLUE ANSI_ESC_CSI "94m"
#define ANSI_ESC_FG_BRIGHT_MAGENTA ANSI_ESC_CSI "95m"
#define ANSI_ESC_FG_BRIGHT_CYAN ANSI_ESC_CSI "96m"
#define ANSI_ESC_FG_BRIGHT_WHITE ANSI_ESC_CSI "97m"

#define ANSI_ESC_STYLE_BOLD ANSI_ESC_CSI "1m"
#define ANSI_ESC_STYLE_UNBOLD ANSI_ESC_CSI "22m"
#define ANSI_ESC_STYLE_DIM ANSI_ESC_CSI "2m"
#define ANSI_ESC_STYLE_UNDIM ANSI_ESC_CSI "22m"
#define ANSI_ESC_STYLE_ITALIC ANSI_ESC_CSI "3m"
#define ANSI_ESC_STYLE_UNITALIC ANSI_ESC_CSI "23m"

#define ANSI_ESC_KILL_SCREEN ANSI_ESC_CSI "2J"
#define ANSI_ESC_KILL_LINE ANSI_ESC_CSI "2K"

#define ANSI_ESC_CURSOR_RESET ANSI_ESC_CSI "H"
#define ANSI_ESC_CURSOR_HIDE ANSI_ESC_CSI "?25l"
#define ANSI_ESC_CURSOR_SHOW ANSI_ESC_CSI "?25h"
#define ANSI_ESC_NEW_SCREEN ANSI_ESC_KILL_SCREEN ANSI_ESC_CURSOR_RESET
void ansi_esc_cursor_pos(uint32_t x, uint32_t y);

#endif // ANSI_ESC_ANSI_ESC_H_
